### PR TITLE
eth_sign expects a hex encoded string as the data message

### LINKED ISSUE #753: eth_sign expects a hex encoded string as the data message
Running the test case will fail.

Against a Hardhat node:
```
Errors encountered in param 1: Invalid value "Hello world" supplied to : DATA
```

Against a Geth node:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 1: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes"}}
```

### PR DESCRIPTION
**Pull request by jyap808**
Fixes #753

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Hi, this is specific to signing a string and converting it to hex. You could sign a hex value and this will fail.

**Comment by jyap808** [comment]
Depends on how you want to resolve this.

eth_sign specifically takes data input as hexutil.Bytes:
```
func (s *PrivateAccountAPI) Sign(ctx context.Context, data hexutil.Bytes, addr common.Address, passwd string) (hexutil.Bytes, error) {
```

https://github.com/ethereum/go-ethereum/blob/c10a0a62c3537fbcf899358e3c3d6be9507fa18c/internal/ethapi/api.go#L1780

**Comment by juanfranblanco** [comment]
Yes exactly the interface it to send a hex string, not a "normal" string, so the fix you are adding is mainly what is expected to do for anyone before using this interface.

So mainly you are doing this before hand ->

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer/EthereumMessageSigner.cs#L41-L44

**Comment by juanfranblanco** [comment]
Apologies.. maybe i was not clear, there is not an issue this is by design.

**Comment by jyap808** [comment]
If it's by design, the documentation and test cases should be modified mentioned in #753.

But yes, I've worked around the issue by converting the string before calling Nethereum.RPC.Eth.EthSign:
```
// Signs in EIP-191 format
        // Note: the address to sign with must be unlocked.
        public async Task<string> EoaSignWithRPCAsync(string rpcURL, string address, string message)
        {
            var client = new Nethereum.JsonRpc.Client.RpcClient(new Uri(rpcURL));
            var ethSign = new Nethereum.RPC.Eth.EthSign(client);
            // eth_sign expects a hex encoded string as the data message
            byte[] bytes = Encoding.ASCII.GetBytes(message);
            string hexMessage = "0x" + BitConverter.ToString(bytes).Replace("-", string.Empty);

            return await ethSign.SendRequestAsync(address, hexMessage);
        }
```

**Comment by juanfranblanco** [comment]
Btw thanks!! If you have any other queries just ping me in discord!

**Pull request closed without merging**
