### PR TITLE
fix keyword collision

### LINKED ISSUE #636: Nethereum.Generators generating parameters with reserved words in C#
I noticed this issue when generating C# code from the contract for ecr-1155 https://github.com/enjin/erc-1155/blob/master/contracts/ERC1155.sol

As an example, one of the functions generated from this contract is

```
        public Task<string> SetApprovalForAllRequestAsync(string operator, bool approved)
```

This does not compile, operator is a reserved word.

## Expected Behavior
The generator should properly prevent the use of reserved words in C#

## Current Behavior
The generator generates code that does not compile

## Possible Solution
If a reserved word would be used, instead use a name that does not collide with a reserved word

## Steps to Reproduce
Generate code for contract https://github.com/enjin/erc-1155/blob/master/contracts/ERC1155.sol

## Context (Environment)
vscode

### PR DESCRIPTION
**Pull request by buddhamangler**
@juanfranblanco 

fixes #636 

This is my attempt to fix reserved word collision with code generation in Nethereum. Some notes...

ParameterABIModel has no awareness or hook back to the code generation type (csharp, vb, etc), so without refactoring it is difficult to determine the most straight forward pr to resolve the immediate issue.  Further complicating this pr is the fact the ParameterABIModel class passes it's calculated input off to another class that is designed to strip some of the very output I need to provide!...aka 'CommonGenerators.LowerCaseFirstCharAndRemoveUnderscorePrefix'.  So given that, it makes me not too confident in my changes since ultimately we need to output strings with a prepended underscore in the vb .net case.

Ultimately you would want to use System.CodeDom more extensively within the code since it has methods that can generate valid identifiers for a given string.  The issue there is that this class is not quite available in .net standard unless you upgrade to .net 5 i think?  Without that each language is a unique situation, which is ultimately why i decided to prepend a static string to call variables and properties for a given language type and do it by passing a generic Func<T> to reduce any coupling there.

All tests pass that I am aware of including the additional test I made.  Happy to hear your thoughts, but I think to make this right would require a bit of a refactor that I am not confident in providing.

Also, this is a breaking change for people clearly.  Especially if they are doing any kind of serialization of these types.

https://stackoverflow.com/questions/5262659/is-there-a-programatic-way-to-identify-c-sharp-reserved-words

### CODE REVIEW

**Comment by juanfranblanco** [comment]
@buddhamangler Many thanks for this, one thing to note all the code gets transpiled to typescript / javascript so this is the reason for keeping it very simple on the core code generator library, a bit of a pain i know, but it helps on the vscode side ;).

**Comment by buddhamangler** [comment]
@juanfranblanco it was pretty late, i'm not sure why I didn't just pass a simple string there instead of a func.  Do you want me to make that modification?

**Comment by buddhamangler** [comment]
I went ahead and made the change, it's definitely simpler.  I think the func thing was an artifact of some other things I was trying.

**Comment by juanfranblanco** [comment]
@buddhamangler hey, btw I have not forgotten about this, I am just thinking of including all the different keywords per each language to avoid having "@" for all properties. Once the first release for templates is out, i will get this sorted and experiment with other generation stuff I want to add.

**Comment by juanfranblanco** [comment]
This has been included in the latest commit, should be shortly in vscode.

**Pull request closed without merging**
