### PR TITLE
Fix up XS proj builder, update Newtonsoft.Json

### PR DESCRIPTION
**Pull request by slothbag**
Just fixed up a small issue with the XS proj file builder. And updated Newtonsoft.Json to 8.0.3

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Portable bouncy is required for other OS / platforms. happy for 8.0.3

**Comment by slothbag** [comment]
The project wont build in XS with the Portable.Bouncy package.  I didn't look too hard into the reason why, I just found switching to regular Bouncy makes it compile.

**Comment by juanfranblanco** [comment]
Maybe this is required http://lastexitcode.com/blog/2014/11/16/InstallingPortableClassLibrariesForXamarinStudio/

**Comment by slothbag** [comment]
Thanks, i'll look into it.

**Pull request closed without merging**
