### PR TITLE
Modified RPC exception handling to return Ethereum error messages.

### PR DESCRIPTION
**Pull request by theonemule**

### CODE REVIEW

**Comment by juanfranblanco** [comment]
There is a logging missing in IPC ill correct it and test it

**Comment by juanfranblanco** [comment]
Thanks!!!

**Comment by theonemule** [comment]
Would it make more sense then to attempt to reuse the stream? Knowing that the error is coming from Ethereum can be useful. Otherwise, it's getting a deserilization error.

**Comment by juanfranblanco** [comment]
I think the problem is having the Code as required on the Error message. Removing that would probably work.

**Comment by theonemule** [comment]
Will that propagate the error message back?

**Comment by juanfranblanco** [comment]
Here https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.JsonRpc.Client/RpcMessages/RpcMessages.cs#L254

**Comment by juanfranblanco** [comment]
Yes, that is what normally happens for any errors.

**Comment by theonemule** [comment]
Cool. 👍 Most helpful then.

**Comment by theonemule** [comment]
Looking at the code, I see where it's doing that.

**Comment by juanfranblanco** [comment]
Your problem (I just realised) is the missing code (as per the issue obviously) which is required by the Error

**Comment by theonemule** [comment]
Sweet.

**Comment by juanfranblanco** [comment]
I have just pushed the change, let me know how it goes. I guess you are already testing it yourself :)

**Comment by theonemule** [comment]
Works great. Good change. Thanks!

**Pull request merged**
