### PR TITLE
Problem with default params in KeyStoreScryptService.cs

### PR DESCRIPTION
**Pull request by xiangxingxing**
According to the RFC:
The CPU/Memory cost parameter N ("costParameter") must be larger than 1, a power of 2, and less than 2^(128 * 1 / 8) = 65536. It may throw error with 'N = 262144' when parsing by nodejs. Maybe the params should be regulated.
[scrypt: maxmem ignored when N >= 65536**r #10003](https://github.com/openssl/openssl/issues/10003)

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Hi, these are the default Ethereum parameters. https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

**Comment by juanfranblanco** [comment]
Continuing on this, you can provide any parameters you want, check this example in the Nethereum Playground http://playground.nethereum.com/csharp/id/1021

**Comment by xiangxingxing** [comment]
> Continuing on this, you can provide any parameters you want, check this example in the Nethereum Playground http://playground.nethereum.com/csharp/id/1021

Many thx! It can fix the problem.

**Comment by juanfranblanco** [comment]
Great, Im glad it helped :).

**Pull request closed without merging**
