### PR TITLE
Support for Microsoft.Extensions.Logging.Abstractions in .net 9

### PR DESCRIPTION
**Pull request by andresgutierrez**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
@juanfranblanco ping

`error NU1608: Warning As Error: Detected package version outside of dependency constraint: Nethereum.JsonRpc.Client 4.26.0 requires Microsoft.Extensions.Logging.Abstractions (>= 6.0.0 && < 9.0.0) but version Microsoft.Extensions.Logging.Abstractions 9.0.0 was resolved.`

**Comment by juanfranblanco** [comment]
Time flies eh? Thank you!

**Comment by andresgutierrez** [comment]
@juanfranblanco Thank you very much for the merge. Is there an ETA for the next release? We would really like to be able to use .NET 9 in our project with this update

**Comment by juanfranblanco** [comment]
This Friday and I'll do a release

**Comment by andresgutierrez** [comment]
Excellent, Thanks!

**Comment by andresgutierrez** [comment]
good morning @juanfranblanco, wanted to know if there's any news about the release? Thanks

**Pull request merged**
