### PR TITLE
Fix nonce integration tests

### PR DESCRIPTION
**Pull request by VladimirTyrin**
* `pollService.PollForReceiptAsync`  calls should be awaited, otherwise we will check that returned tasks are not `null`'s (which is always true), not task results.
* async methods in `Parallel.ForEach` loop will continue executing after loop completion, we should wait for them synchronously (or use something like `Task.WhenAll` / `System.Threading.Tasks.Dataflow` classes)

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Yes those were rather silly typos. But very interesting the fact on the parallel for and forcing sync to avoid continuing the loop, I'll do some further checks on that.

**Comment by juanfranblanco** [comment]
Sure it is a async void :) Thanks.

**Comment by VladimirTyrin** [comment]
Why didn't you merge this?

**Comment by juanfranblanco** [comment]
I haven't had time to test it..

**Comment by VladimirTyrin** [comment]
Oh, ok.
Thank you for your library :)

**Comment by juanfranblanco** [comment]
Testing on the fixes on the typos of my testing! ;) Thanks!!!

**Pull request merged**
