### PR TITLE
Anonymous events support added

### PR DESCRIPTION
**Pull request by frostiq**

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Awesome :) If not too much ask can you add an integration test for an anonymous event?

**Comment by juanfranblanco** [comment]
Also, IsLogForEvent, is rather tricky one as the signature is checked. Although this is Anonymous but also the signatures might not match. In simplistic terms if you know that you are consuming an anonymous event it could be assumed that is your responsibility to match it.

**Comment by frostiq** [comment]
Sure, we will add integration tests for this case

**Comment by Tammind** [comment]
Hi @juanfranblanco!

We've updated PR. Tests are added.

**Comment by frostiq** [comment]
@juanfranblanco, please take a look at your earliest convenience

**Comment by juanfranblanco** [comment]
@frostiq Hi just got back from holidays, I will merge it ASAP thanks :)

**Comment by frostiq** [comment]
Thank you @juanfranblanco!

Please let us know when you are going to release new nugets

**Comment by juanfranblanco** [comment]
It is planned for next week, you can use CI for the time being if you want.

**Pull request merged**
