### PR TITLE
Resolved SecureRandom does not have an implementation of GetBytes

### PR DESCRIPTION
**Pull request by ovaishanif94**
Update NBitcoin package to resolve IRandom latest NBitcoin's interface.

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Hi adding Span will need to be part of a pragma to be compatible with older versions of dotnet, also need to validate any changes to NBitcoin to move to the current version.

**Comment by ovaishanif94** [comment]
When I am creating new HD account they showed error "does not have any implementation of IRandom Getbytes" so when I look into it I sawed in NBitcoin newer version there is Span GetBytes method added.
I used this Nethereum.HDWallet package with latest NBitcoin.Altcoins package

**Comment by juanfranblanco** [comment]
Edit 2: Or is the change mainly to be able to upgrade to NBitcoin

**Comment by juanfranblanco** [comment]
Ah ok so it is mainly to upgrade NBitcoin, yeah i need to check any issues with older versions.

**Comment by farukterzioglu** [comment]
Any chance this is coming any time soon, need to update some services to .Net 3.1 and this is blocking me.

**Pull request merged**
