### PR TITLE
Add generator support for Truffle style compiled contracts

### PR DESCRIPTION
**Pull request by ConnorChristie**
## Overview
This PR adds support for reading JSON based compiled contract definitions resulting from a Truffle compile command. Without this, work must be done to extract the ABI from the json file before generating the Nethereum based contract definitions.

## Major things modified:
* Refactored `GeneratorConfiguration` and `ABIConfiguration` into `ABICollectionConfiguration` and `ABIConfiguration` which contain the contents that are saved to disk in the form on the config objects.
* Created `ContractDefinition` and `Generator` models to provide a clean interface when referencing ABI / Bytecode of a contract and the information detailed by a single contract.
* Created an additional generate command `generate from-directory` that processes a directory of JSON based contract build artifacts.

## Testing done:
* Made appropriate modifications to unit tests and ensured they all still pass.
* Tested locally by generating from:
    * csproj
    * directory of compiled truffle contracts

### CODE REVIEW

**Comment by juanfranblanco** [comment]
@Dave-Whiffin Assigning to you, the Console is your bit :D

**Comment by juanfranblanco** [comment]
One thing to note, forcing to generate from compiled directory to use the Truffle format is not correct. It needs a specific command for that. The build may include the solc output, which is the standard.

**Comment by juanfranblanco** [comment]
Another thing to note, is that have been removed the parameters (whilst optional) for Namespace and other settings.

**Comment by Dave-Whiffin** [comment]
Hi Connor - thanks for your input.  I am looking at this PR for you.    

Most of it looks good - nice work.  I can see the need for the new functionality.

I would echo Juan's initial comments / concerns, these do need to be addressed before we could accept the PR.

1 - The command name should be truffle specific . "generate from-truffle" or "generate from-truffle-directory".  
2 - Code generation parameters have been removed.   I am not sure if this an oversight or on purpose.  The specific parameters are normally assigned automatically by convention so in most use cases it wouldn't be a problem.   But, the old code did allow these parameters to be specified from a config file which gives the user more control of their namespacing.   These parameters were used by the code generation wrapper.

ABI Configuration properties which have been removed:
CQSNamespace
DTONamespace
ServiceNamespace

Feel free to message me to discuss, it would be good to learn more about your use cases.

**Comment by ConnorChristie** [comment]
@Dave-Whiffin The reason I removed the CQS, DTO, and Service namespace config settings was because at first glance I thought they were always being generated based on the "default" format by just prepending the base namespace.

I guess I would ask, are there any cases where a user wants to specify custom sub-namespaces for the three folders? I can easily add the functionality back but I imagined it being cleaner and simpler if the generator just took care of naming those folders.

As for the command name - I will change the name to be specific to truffle.

**Comment by Dave-Whiffin** [comment]
Thanks for making the command change - we do need those extra namespace config settings though.  The generator does create defaults and this is the norm - but they are there for a sound reason even if they won't be used very often.    Much appreciated, Dave.

**Comment by Dave-Whiffin** [comment]
Thanks Connor - I'll merge this in and add some unit tests for the new functionality (normally we'd require these in place before accepting a PR).  We're grateful for your contribution, thanks again.

**Pull request merged**
