### PR TITLE
+ gasPrice parameter

### PR DESCRIPTION
**Pull request by tanderbold**

### CODE REVIEW

**Comment by tanderbold** [comment]
Build a release please. I use a package in my project.

**Comment by juanfranblanco** [comment]
Thanks for this, a package won't be available for a while (release) as I am currently refactoring.

You can use the TransferFunction message to provide the gas like in here:

https://github.com/Nethereum/Nethereum.CQS.SimpleTokenTransfer/blob/master/Nethereum.CQS.SimpleTokenTransfer/Program.cs#L111-L155

**Comment by tanderbold** [comment]
Thank you, I have wrote some code around the library.

**Comment by juanfranblanco** [comment]
Closing this as the Token Library was updated to use the CodeDefinitions in 3.0

**Pull request closed without merging**
