### PR TITLE
WIP: GSN support

### PR DESCRIPTION
**Pull request by aquiladev**
I already discussed with @juanfranblanco that the module is out of scope Nethereum, but I would like to have some feedback about the solution.
The module allows using [Gas Station Network (GSN)](https://docs.openzeppelin.com/openzeppelin/gsn/what-is-the-gsn) for transacting from accounts without Ethers.

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Thanks @aquiladev , that is pretty cool. I am still worried that the intercepting layer is too low level. Having a  custom transaction manager may be a better fit, as it can use the Account privateKey to do the signing. I need to have a proper look.

**Comment by juanfranblanco** [comment]
Also the relay client needs to be more visible.

**Comment by juanfranblanco** [comment]
Just some heads up, I still have not had time to fully check this out, but I really like it. It will be great to have the server side also in Azure + AWS (I was thinking of using Functions, Lambda, serverless)

**Comment by aquiladev** [comment]
@juanfranblanco I believe you are talking about the relayer itself, which is separate applicate. This PR contains a piece of code that allows communicating with GSN relayer. It finds relayer, prepares the right model for the relayer, calls relayer and verify results from relayer.

**Comment by juanfranblanco** [comment]
Yeah that is what I meant, but surely something I can do, don't worry.

**Comment by juanfranblanco** [comment]
@aquiladev Happy new year!!  Just a quick check on this PR. 
s it nearly finished in your side?
Is there a test backend server we can use to validate this? 
Should we reach out the open zappeling guys?

**Comment by aquiladev** [comment]
## Current state
The current version can be treated as a basic implementation. We use this version in our project, it works pretty stably. I use it on Rinkeby network.
 
## How to check it?
I don't have any test environments. I need to think about it. I may create an example or put explanations on README file.

## Things to improve
There is a Relay selection policy in the project. The policy selects the first available Relay. Currently, Rinkeby has registered only 2 Relays(I think) and the policy is good enough for the current situation. When there will be more registered Relays the policy will not be efficient, we will need a different policy, it can be based on reputation. I plan to work on a new policy. 

## OpenZepplin
I've created a [topic](https://forum.openzeppelin.com/t/gsn-support-in-nethereum/1441/2) on the forum while ago. We can use it to communicate with OpenZepplin guys

**Comment by juanfranblanco** [comment]
Ah nice!, So it is not WIP, it is working :). Yes for integration testing or CI it will be necessary some realistic or mockup service.  Realistically it does not need to be autodeployed for CI, but something that can be ran locally or point to an existing endpoint. I do that in some scenarios with Infura.

There are some restructuring that I would love to have, but before I start testing those ideas, (which might be wrong) I need to know that I don't break anything :).

**Comment by juanfranblanco** [comment]
It will be nice to have an example in the future integrated in our future example https://github.com/Nethereum/Nethereum.eShop

**Comment by juanfranblanco** [comment]
Well as it is actually functional I will merge, more testing, docs, etc and even redesign can be added later.

**Comment by aquiladev** [comment]
Ok, I'll take a look at eShope, integration testing, documentation this week.

**Comment by juanfranblanco** [comment]
@aquiladev Thanks, that will great. Also don't build your hopes on the eShop, it just started :D The readme gives you some idea of the goals.

**Pull request merged**
