### PR TITLE
RpcClient Connection fix

### PR DESCRIPTION
**Pull request by nettrash**
Under heavy load, the previously used solution eventually led to a situation where it was impossible to obtain a connection. Because HttpClient is designed to be reused within the lifetime of a process, added a dictionary of created instances of HttpClient relative to baseUrl. In addition, I enabled the settings of non-termination of connections (necessary for re-use) and made the limit of connections in the fields of the RpcClient class. The tests showed no problem with the inability to allocate the connection and confirmed the limited growth of open connections, indicating successful re-use.

### CODE REVIEW

**Comment by juanfranblanco** [comment]
I don't understand this pull request, the http client (swap) is designed to keep only 1 Http client in memory BUT to support older versions of Netstandard a rotation is done to avoid issues with dns changes.

**Comment by juanfranblanco** [comment]
Now.. it does seem to resolve another problem, which is very heavy load. Will this valid as another RpcClient?

**Comment by nettrash** [comment]
I will try to explain my proposals for this change. If we work with multiple baseUrl we want to get a single HttpClient for each specific baseUrl. Now in a project that uses multiple contracts we have multiple HttpClient for the same baseUrl. The application makes hundreds of requests per second to the local geth. In this usage scenario, we encountered a problem of insufficient connections, as it remains in the TIME_WAIT state. Added ServicePoint settings to re-use current connections. We are currently using .NET Core 2.2.
```
ServicePoint.ConnectionLimit   

      .NET Core
      3.0 2.2 2.1 2.0  

      .NET Framework
      4.8 4.7.2 4.7.1 4.7 4.6.2 4.6.1 4.6 4.5.2 4.5.1 4.5 4.0 3.5 3.0 2.0 1.1

      .NET Standard
      2.1 2.0  

ServicePoint.ConnectionLeaseTimeout  

      .NET Core  
      3.0 2.2 2.1 2.0  

      .NET Framework  
      4.8 4.7.2 4.7.1 4.7 4.6.2 4.6.1 4.6 4.5.2 4.5.1 4.5 4.0 3.5 3.0 2.0  

      .NET Standard
      2.1 2.0
```  

> Will this valid as another RpcClient?
It is not very clear what is meant.

**Comment by juanfranblanco** [comment]
The RpcClient will only handle one baseUrl, so the dictionary won't work. The best thing is to create multiple intances of Web3 for each url.

Yes ServicePoint is not available until Netstandard 2.0 so it is not available in lower versions.
The servicePoint settings with some example of stress testing could be included with pragmas targetting other versions.

The CancellationToken memory leak / bug in .Net after it surely helps on the lower versions, it seems to be fixed in .Net core 2.1

**Comment by juanfranblanco** [comment]
> Will this valid as another RpcClient?

The thought is that if you are having specific needs, another type of RpcClient can be created instead of the default one. But I think we can pick some of the thoughts and combine with the current.

Also an emphasis is that this is designed to work with a single httpclient, the rotation is specific the dns issues and lack of ServicePointManager implementation in lower versions.

**Comment by nettrash** [comment]
I agree with your opinion. For our purposes, we will just use our version of RpcClient. Combining the entire proposed piece seems really redundant.

**Comment by juanfranblanco** [comment]
@nettrash my point on the dictionary is that you create the url with the absolute uri, which is defined in the constructor https://github.com/Nethereum/Nethereum/blob/8b89410f362e1f91fc704b2a82879935e1e55740/src/Nethereum.JsonRpc.RpcClient/RpcClient.cs#L101

so the great value add is the service point manager settings which can be targeted to the supported versions. https://github.com/Nethereum/Nethereum/blob/8b89410f362e1f91fc704b2a82879935e1e55740/src/Nethereum.JsonRpc.RpcClient/RpcClient.cs#L109-L111

Now if that adds value, the only thing is not to provide a rotation of http client on the new versions of .Net as it wont' be necessary using the same pragma. Ill think about it and you can give it a spin and see if it solves your problem.

**Comment by nettrash** [comment]
if to continue discussion, I want to pay attention that the dictionary is offered to make static, that is it will be uniform. and will contain clients under each URL used in the application.

but I agree that backward compatibility requires maintaining rotation.

I have to dive into the context of the dns problem that was earlier. I can't remember what the trouble was.

**Comment by juanfranblanco** [comment]
Ahh now I see, it is static the dictionary. Yeah, this is a very specific scenario, but nevertheless an interesting one, which may fit in another RpcClient (there is a SimpleRpcClient so it is not a problem to have other options). What is the lifecycle of the httpClient(s)?

**Comment by nettrash** [comment]
httpClient lifecycle.

Now it turns out that each new instance of RpcClient will create an entry about the HttpClient instance in the single process Directory<string, HttpClient> if there is no HttpClient instance for the baseUrl used. And such an object lives until the end of the application process. 

Thus, we get a minimization of the cost of creating clients and some grouping of connections by baseUrl. 

Yes, now there is a mechanism in ASP.NET called HttpClientFactory, but it cannot be applied at this location. Of course, we can add the logic of removing HttpClient when not in use for a long time, but a scenario with long-term non-use seems unlikely, since applications with RPC tend to use It all the time.

**Comment by nettrash** [comment]
@juanfranblanco should I add this client option as another one?

**Comment by juanfranblanco** [comment]
Apologies I have been thinking about this, and see what is the best option. I believe the best solution is to accept an httpClient as a parameter, similar to the SimpleHttpClient which can be configured etc or maybe created using the HttpClientFactory. So if you want to keep a singleton / static dictionary that could be from another class which acts as a Factory, similar to the httpClientFactory.

**Comment by nettrash** [comment]
I can rewrite this part of the code to accept HttpClient as a parameter, additionally adding the HttpClient factory that performs grouping by the selected parameters.

I'm ready to change the code. Changing? Or should the merge request be closed?

**Pull request closed without merging**
