### PR TITLE
RPC: implement Equals for TransactionReceipt

### PR DESCRIPTION
**Pull request by knocte**

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Thanks @knocte , you could get away with Block Hash and Transaction Hash, even just Transaction Hash, depending the context of the equality.

**Comment by juanfranblanco** [comment]
Also equality of contract addresses might be an issue due to the different capitalisation of address for checksums.

**Comment by knocte** [comment]
> you could get away with Block Hash and Transaction Hash, even just Transaction Hash, depending the context of the equality.

What if different ETH nodes give different receipt details for the same transaction? In my case, I would prefer those receipts to be different in this case, because I'm measuring consistency in their responses.

> Also equality of contract addresses might be an issue due to the different capitalisation of address for checksums.

This one is a good point, thanks for improving that in your next commit!

**Comment by juanfranblanco** [comment]
Ahhh great point two different chains, never thought of that. Although hashes will be rather difficult to be the same, still it is a possibility, and we have also the logs.

**Pull request merged**
