### PR TITLE
SIWE Recap Functionality

### PR DESCRIPTION
**Pull request by jaerith**
This PR has the initial revision for SIWE Recap functionality.

Even though this code builds in my test project, it does not currently build in the Nethereum repo, due to a number of issues - including:

* Cannot find IEnumerable.ForEach
* Cannot find Encoding.ASCII

### CODE REVIEW

**Comment by jaerith** [comment]
> @jaerith shouldn't be this part of Core?

I was going back and forth on that one.  Since Recap is considered an extension of SIWE, I wasn't sure whether or not it belonged in Core.  But since you have much more experience with organizing namespaces, I'll trust your final decision over mine.

**Comment by juanfranblanco** [comment]
@jaerith well Siwe.Core.Recap.. the reason for Core is that is more portable and does not need many dependencies.

**Comment by jaerith** [comment]
Okay, they've been moved to the Siwe.Core project.

**Comment by juanfranblanco** [comment]
And tests ;)

**Comment by jaerith** [comment]
Whoops!  I also hadn't taken note of SonarLint's warnings before, so I just did a little refactoring.

**Comment by jaerith** [comment]
I also added an extension method that validates the Statement and Resources in the SIWE message, making sure that they match.  Though now, in addition to the ForEach extension method not being found (within the context of the opened Nethereum solution), Visual Studio says that it can't find the String.Split() method where the parameter is a string.  Is this due to backward compatibility, as a setting within the solution?

**Pull request merged**
