### PR TITLE
Support for .NET Core

### PR DESCRIPTION
**Pull request by tritao**
I tried to keep all changes backwards compatible, so everything should be the same

First commit updates all projects to use the variables for target frameworks and new csproj syntax.

Second commit provides minor C# and build fixes for .NET Core support, as well as new solution without unsupported Unity, Desktop and Web projects.

### CODE REVIEW

**Comment by juanfranblanco** [comment]
As per gitter comments, all the core projects support netstandard1.1 where possible so .net core is supported. Not all projects support Unity3d .net 351 so the changes will break the solution. 
Portable project is generated using the utility project which also does not support Unity3d, so just find and replace all targetframeworks with unity is not a solution. 

Mac users can build the core projects and not utilities if needed, obviously is a dependency to unity3d.

**Comment by juanfranblanco** [comment]
Also removing all the BigInteger for net351 will break the lack of support for unity3d. This is required to be in Nethereum.Hex for backwards compatibility as the Mono implementation was broken (BigInteger) and of course there was none in normal .net. This implementation uses parts of .Net core and mono in 4.6 to support downgrade.

**Comment by juanfranblanco** [comment]
BTW Many thanks, if it works for you locally (it should) feel free to work that way :). Either way pull request will be only accepted for one small file at a time.

**Comment by tritao** [comment]
Just a clarification: As I said to you on Gitter, I did not remove BigInteger files. This is just how modern csproj works, there is no need to specify them on the project files as they are picked up by MSBuild now. It also works for .NET Framework projects.

I hope you reconsider in the future your policy for supporting .NET Core, since it is the future of .NET. Right now it makes no sense for you say .NET Core is supported when the project does not even compile with .NET Core tools.

Anyway, I will keep .NET Core branch on my fork, if anyone needs it.

**Comment by juanfranblanco** [comment]
.Net core is supported, it is netstandard1.1

**Comment by juanfranblanco** [comment]
Re BigInteger, these are linked files in a separate project, So yes, it is needed to have them there. I have chosen this to remove noise of the project, testing, and remove the need for Unity3d users to add a specific library (which may lead to major issues when doing aot and trimming). I do understand the new project format, very well.

**Comment by juanfranblanco** [comment]
Also there are projects, that have to target other netstandard versions (sadly) but that is the case, IPC or HdWallet. 

I applaud your intention, but there has been an issue of understanding of why each project targets different frameworks, or an understanding of why each project is structured some way. 

Just because it compiles on your machine in .net core, it does not mean you have solved the problem. So just contributing to an open source project and changing everything without an understanding of why, does not help. I understand that in the Mac world everything seems like .Net core and the rest can go, but it is not like that.

**Comment by tritao** [comment]
Yeah, I just realized I did not need to touch that BigInteger.Net351 project at all, my bad.

I understand and respect your decision to keep project Windows-centric to support as many targets as possible. I just think with some minor changes, it would be possible to keep the support you already have on VS to target multiple frameworks, AND also support .NET Core, with some MSBuild defines. There's no reason you should not be able to support everything.

But it's all good. Once you're open to that idea, as I said before, I'm willing to do the changes required and merge it back.

**Comment by tritao** [comment]
I sent the PR for review, obviously willing to do the changes required if you had told me what needed to be done. Of course me being new to the project I do know the reason for some things, that is normal. I could have even keep exactly the same target frameworks in the original projects when targetting .NET Framework, and just use new one for .NET Core case.

**Comment by juanfranblanco** [comment]
The idea is there, but everything has to compile to everything. It is not good to compile just to netstandard, to later find out that that specific project does not work in .net351 or .net451, or that section of the code. I know it is an utter pain, but that is the way it is and it will continue that way. Targetting the lowest common possible will help later on when trying to build for WASM. Including EVM, or other networking.

**Comment by juanfranblanco** [comment]
Yes, it is all cool :). I understand your prompt needs, mainly you need something to compile so it can be tested on your current environment, and work with that. I would think about something after the holidays, which will be similar to what you have done.

**Comment by juanfranblanco** [comment]
Or mainly an extended version ;)

**Pull request closed without merging**
