### PR TITLE
Eip155 nits

### PR DESCRIPTION
**Pull request by knocte**

### CODE REVIEW

**Comment by juanfranblanco** [comment]
PrimitiveObsession anti pattern :). On an enterprise setting or if you scale with sidechains / plasma which have a specific chainId you would not deal with the Chain enum ever.

**Comment by knocte** [comment]
Still, there are ways to avoid PrimitiveObsession in this case :D Especially in F# that has type aliases, e.g. `type ChainId = BigInteger` ;)

**Comment by juanfranblanco** [comment]
A side note, when chainIds become BigIntegers as a norm, the enum is not going to work. But that should not be something to worry now at all, as the main public chains will still be an int32.

**Comment by knocte** [comment]
When that happens, we can transform the Chain enum into a static class that has public readonly members that map to BigInteger values.

**Comment by juanfranblanco** [comment]
Yes, but I don't see that happening tomorrow. And yes, I'm pushing that now.

**Pull request merged**
