### PR TITLE
Enhancement: Adding new constructor that accepts aws kms client interface parameter.

### PR DESCRIPTION
**Pull request by kjmoraji**
AwsKmsExternalSigner now supports passing interface rather than concrete key management service client.

### CODE REVIEW

**Comment by kjmoraji** [comment]
Hi @juanfranblanco 

Please let me know if you have any comments or questions about this pull request. Specifically any concerns about the new constructor on the web3quorum class.

**Comment by juanfranblanco** [comment]
Web3Quorum had those restricted constructors to enforce using either the UnlockedAccount or the QuorumAccount with their corresponding TransactionManagers. I guess that you want to use AWS to sign this? What are your requirements?

**Comment by kjmoraji** [comment]
> Web3Quorum had those restricted constructors to enforce using either the UnlockedAccount or the QuorumAccount with their corresponding TransactionManagers. I guess that you want to use AWS to sign this? What are your requirements?

That's correct. The idea is to pass any type of account (and use its corresponding transaction manager). In my particular case I'm passing an external account (which uses the AwsExternalSigner for transaction signing).

I know the new constructor is quite of broadly open (since its accepting any type of account). So, another approach is to add a new constructor for the specific account type (in this case ExternalAccount) and then keep the new generic constructor with a higher privacy level (maybe internal or private).

**Comment by juanfranblanco** [comment]
Adding the External Account directly wont work here as it will need a new QuorumExternalAccountTransactionManager, which will handle the privateFor etc.

**Comment by kjmoraji** [comment]
> Adding the External Account directly wont work here as it will need a new QuorumExternalAccountTransactionManager, which will handle the privateFor etc.

Hi @juanfranblanco 

Thanks for your response,

I think I will try to formulate the pull request as the question that I'm trying to address.

How can you build a Web3Quorum (and it's corresponding QuorumExternalAccountTransactionManager) to send transactions that are offline signed with using AWS KMS? The QuorumAccount strongly relies on having beforehand the account private key (and behind the scenes using EthECKey with that private key).

That's why I was introducing the ExternalAccount constructor (which will behave kind of the same as the UnlockedAccount). Both having it's own transaction manager type (which is not QuorumExternalAccountTransactionManager). Both of them knowing nothing about privateFor etc.

**Comment by juanfranblanco** [comment]
Unlocked account works differently as it is unlocked does not participate on private txns. The best thing is to raise an issue as opposed to a pull request. Now this needs an understanding of the version of quorum.

**Comment by kjmoraji** [comment]
> Unlocked account works differently as it is unlocked does not participate on private txns. The best thing is to raise an issue as opposed to a pull request. Now this needs an understanding of the version of quorum.

Hi @juanfranblanco 

I opted in to do not request pulling any changes on Quorum classes as I need to review it in depth how to approach it.

Instead, I'm now only pulling changes on the AWS KMS external signer class.

**Comment by juanfranblanco** [comment]
Can you remove the regions? Just to see only the functionality that had changed.

**Comment by kjmoraji** [comment]
> Can you remove the regions? Just to see only the functionality that had changed.

Hello @juanfranblanco.
It's done, I have removed the region statements.

**Comment by juanfranblanco** [comment]
Finally if you could squash the commit, just to see the changes that will be great.

**Comment by kjmoraji** [comment]
> Finally if you could squash the commit, just to see the changes that will be great.

Hello @juanfranblanco 

It's done. The pull request is now only with 2 commits.

**Pull request merged**
